### ISSUE TITLE
Logging job output

### ISSUE THREAD

**Issue by worr** [banzaicloud/logging-operator#132]
Currently log output of jobs is not picked up by the current generated `fluentd` configuration. For clusters that have job-heavy loads, this makes it difficult to aggregate that data.

A naïve fix is to add an additional rule:

```diff
diff --git a/pkg/resources/fluentd/config.go b/pkg/resources/fluentd/config.go
index 6b09105..0ad762a 100644
--- a/pkg/resources/fluentd/config.go
+++ b/pkg/resources/fluentd/config.go
@@ -85,6 +85,11 @@ var fluentdInputTemplate = `
     pattern ^(.+)$
     tag $1.${tag_parts[0]}.${tag_parts[1]}
   </rule>
+  <rule>
+    key $.kubernetes.labels.job-name
+    pattern ^(.+)$
+    tag $1.${tag_parts[0]}.${tag_parts[1]}
+  </rule>
 </match>
 `
 var fluentdOutputTemplate = `
```

However, while this would capture exactly what I want, I'm not sure if you'd prefer it to be configurable or if it should be hard-coded like the rule for retrieving logging from applications. I'm happy to submit a diff either way.

**Comment by pepov** [comment]
Hey, please note that we are working on a new version of the operator where this will be more flexible and easier to achieve. If you need this patch however in the current version as well, then it should be configurable with a flag in the fluentd CRD at least. 

One more thing, I think `tag_parts[2]` is missing from the end of the tag, otherwise we would lose the original "head".

**Comment by pepov** [comment]
@worr the new version of the operator will leverage this plugin for constructing tags from the incoming log record metadata: https://github.com/banzaicloud/fluent-plugin-tag-normaliser

I beleive this could replace the currently hardcoded rewrite_tag_filter rules in the current version as well. If you would be willing to contribute it into the current operator it's more than welcome, otherwise stay tuned and follow us on slack for updates on v2: https://slack.banzaicloud.io/

**Comment by pepov** [comment]
related issue: https://github.com/banzaicloud/logging-operator/issues/125

**Comment by worr** [comment]
Hmm, is there a timeline for v2? That'd determine whether or not I'd contribute it to the current operator, honestly. Is that a better thing to ask in the Slack?

**Comment by pepov** [comment]
We are working on it to be available for preview in a month, preferably with all the existing features of v1 and then we will need some time to stabilize, but hopefully not more than a few weeks again.

**Comment by tarokkk** [comment]
Logging-operator v2 is out and [tag-normaliser](https://github.com/banzaicloud/logging-operator/blob/v2/docs/plugins/filters/tagnormaliser.md) is available.
