### ISSUE TITLE
[feature request] Support vector.dev instead of fluentd

### ISSUE THREAD

**Issue by Slach** [banzaicloud/logging-operator#283]
I'm always frustrated when I think about the efficiency of log processing on each server, fluentd written on Ruby and it's not really fast solution

Could you look to use http://vector.dev/ instead of fluentd as an option?

**Comment by tarokkk** [comment]
Can't help with your frustration, but let me add some answers here. The starting point is that this operator is built on, depend and managed the Fluent ecosystem.
- `not really fast solution` is a subjective unit, and especially in this case I assume is fueled by a Ruby vs Rust comparison. What end users require, is a simple, robust, trusted and widespread solution to move and work with logs. Does a [2TB/day](https://banzaicloud.com/blog/logging-operator-monitoring/) log forwarding solution built on the Fluent ecosystem `fast` enough? It's subjective again, and fulfills customer requirements. 
- next item probably will be resource consumption? Is that a valid point? It can be, if it's a real `issue` and people can't get over it. Note that this usually is measured in proportion to the resources consumed by the overall system. 
I have seen some of the metrics published and in many areas they are promising, however this, I believe it's not enough to ditch the whole Fluentd out, rewrite the code and move all the existing users into an ecosystem which is by far inferior to the Fluent one (features, external support/contributors, industry adoption, I could go one here ...). 
Don't get me wrong - we have our own issues with Fluent (are we happy writing plugins in Ruby, I guess not) but at this time this is the `standard` logging ecosystem in Kubernetes.

**Comment by tarokkk** [comment]
Hi!

Can't help with your frustration, but let me add some answers here. The starting point is that this operator is built on, depend and manage the Fluent ecosystem.
- `not really fast solution` is a subjective unit, and especially in this case I assume is fuelled by a Ruby vs Rust comparison. What end users require, is a simple, robust, trusted and widespread solution to move and work with logs. Does a [2TB/day](https://banzaicloud.com/blog/logging-operator-monitoring/) log forwarding solution built on the Fluent ecosystem `fast` enough? It's subjective again, and fulfils customer requirements. 
- next item probably will be resource consumption? Is that a valid point? It can be, if it's a real `issue` and people can't get over it. Note that this usually is measured in proportion to the resources consumed by the overall system

I've seen some of the benchmark published and in many areas they are promising, however this, I believe it's not enough to ditch the whole Fluentd out (there are several question like Kubernetes label based routing, exposing metrics, custom plugins) rewrite the code and move all the existing users into an ecosystem which is by far inferior to the Fluent one (features, external support/contributors, industry adoption, I could go one here ...). 
Don't get me wrong - we have our own issues with Fluent (are we happy writing plugins in Ruby, I guess not) but at this time this is the `standard` logging ecosystem in Kubernetes. 

However we will discuss this with the vector.dev maintainers to see their opinion as well.

Happy Logging

**Comment by binarylogic** [comment]
I was just about to open a similar issue! @Slach we're working closely with a number of large k8s deployments to ensure Vector's k8s integration is thoughtful and battle-tested. Email us at vector@timber.io if you're still interested.

---

@tarokkk @ahma we really like what you've done with the logging operator. The general architecture and attention to detail are 👌. We're big fans of Banzai Cloud and would love the opportunity to work together. I completely understand your concerns above, but I do think if you gave Vector a shot it would win you over. I'm biased, of course 😄.

That said, we're starting to explore a Vector based logging operator and would love it if we could work Vector in as an option. Would you...

1. Consider a pull request that added Vector as an option? (we'd actively help maintain it)
2. Support a fork if we maintained it?

I completely understand otherwise! We just want to help, our goal is to make these sort of pipelines so reliable that users quit having to think about it.

If it's easier, I'd love to meet. There's a lot I'm leaving out here. For example, a few of the companies we're working with previously used this operator, and at the very least, I could provide some helpful feedback. Feel free to email me ben@timber.io .

Thanks for hearing me out!
