### ISSUE TITLE
Provide serviceAccountName to configuration

### ISSUE THREAD

**Issue by tarokkk** [banzaicloud/logging-operator#31]
**Describe the problem**
We should provide an easy way to manage the RBAC configuration for fluent-bit and fluentd deployment.

**Proposed solution**
Provide a service account override configuration option to skip the RBAC creation part. Although we should provide usable defaults if not set.

**Comment by MihaiAnei** [comment]
It will help a lot in the context of this operator being deployed on EKS and be able to use the new IAM-Role/ServiceAccount authorisation. No need to create Users and have AWS Credentials in Output.

**Comment by malletgu** [comment]
I just made logging-operator and fluentd work together and will push the changes I made a bit later after tidying them. :smile:  

The problems I encountered were : 
- The service account used by fluentd can't be changed for the moment through the operator
  - resolved by granting access to the default service account as it runs in a protected namespace
- The fluentd process doesn't have read access to the injected token by the aws eks mutatingwebhook (the path to this token is `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` from within the pod). This is caused by the docker image using fluentd user and the token is read-only by root per default. (see https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8 for more context)
  - resolved by setting `securityGroup: { "fsGroup" : 65533}` in the fluentd stateful set, `65533` being fluent user group id.
 - The fluentd process was then not able to access to region (I don't really know why).
   - This was fixed by adding `AWS_REGION` as an environment variable for the fluentd container.

**Comment by tarokkk** [comment]
> I just made logging-operator and fluentd work together and will push the changes I made a bit later after tidying them. 😄
> 
> The problems I encountered were :
> 
> * The service account used by fluentd can't be changed for the moment through the operator
>   
>   * resolved by granting access to the default service account as it runs in a protected namespace
> * The fluentd process doesn't have read access to the injected token by the aws eks mutatingwebhook (the path to this token is `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` from within the pod). This is caused by the docker image using fluentd user and the token is read-only by root per default. (see [aws/amazon-eks-pod-identity-webhook#8](https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8) for more context)
>   
>   * resolved by setting `securityGroup: { "fsGroup" : 65533}` in the fluentd stateful set, `65533` being fluent user group id.
> * The fluentd process was then not able to access to region (I don't really know why).
>   
>   * This was fixed by adding `AWS_REGION` as an environment variable for the fluentd container.

Thank you for sharing your experiences. I think they are really helpful!

**Comment by tarokkk** [comment]
We added some ServiceAccount and PSP enhancement. If you need anything else to support your use-case  please open a new issue.

**Comment by AlKapkone** [comment]
Hello, is it possible to use AWS EKS IRSA (service account mapping to IAM roles) with logging-operator fluentd ?
