### ISSUE TITLE
Make fluentbit config more customizable

### ISSUE THREAD

**Issue by pbecotte** [banzaicloud/logging-operator#344]
**Is your feature request related to a problem? Please describe.**
Am experimenting with your logging-operator- seems pretty cool! Hit a rough spot though. I need a lua filter in my fluentbit config. (in my case, moving labels k8s.mycompany/app to a special mycompany object at the document root). 

I was able to make it happen by creating my own configmap.

**Describe the solution you'd like**
I'd like the fluentbit config to be broken out a bit more. Providing the whole thing or not changing anything is too big of a change. The custom configmap worked fine- but it took me quite a few tries to get the rest of the config right to match the way the fluentd was configured (and I'm still not sure I am 100% there). Maybe an `extra filters` or `extra parsers` field or similar.

**Comment by sermilrod** [comment]
We have the need to extend the parsers with a few custom ones and I see nowhere in the documentation how to do it. It would be good to have an interface to provide that extra config and extend the list of parsers

**Comment by tarokkk** [comment]
The problem you stated is exactly the reason behind the restricted configuration of fluent-bit.

> "The custom configmap worked fine- but it took me quite a few tries to get the rest of the config
> g right to match the way the fluentd was configured (and I'm still not sure I am 100% there)."

The idea behind the logging-operator is to **collect and enrich** logs with `fluent-bi`t then **process and transfer** them with `fluentd`. There are enormous amounts of ways you can configure a logging stack with fluentd and fluent-bit. That's why we created basic boundaries to prevent users from breaking log flows via misconfiguration (it is still pretty easy thought). If you start moving logics to fluent-bit (lua filters, parsers etc) instead of fluentd it is nearly impossible to verify that the mechanics behind routing logs, rewriting tags etc… will work as intended. Don't forget that logging-operator is tightly coupled with kubernetes metadata attached to logs and so on.

Moreover if you move more and more logics to fluent-bit the load won't be equally distributed amongst nodes there would be some hot spot. This shouldn't be a problem in general but can be tricky in special cases. Fluentd however, can be pinned to nodes designated to care for logging workloads and you can scale them individually in contrast to fluent-bit daemonset.
I know that fluent-bit is evolving rapidly but there are still several outputs and plugins that just simply not yet working there. By design fluentd is much easier to extend with plugins and defining distinct flows via labels.

I would be really surprised if there would be a use-case that fluent-bit can solve but fluentd can't. (Considering that fluentd can run ruby plugins which provides even more features than fluent-bit lua filter)

> "in my case, moving labels k8s.mycompany/app to a special mycompany object at the document root"

I think your use-case can be easily solved via [record transformer](https://docs.fluentd.org/filter/record_transformer)
