### ISSUE TITLE
supports log collection from external storage and host files

### ISSUE THREAD

**Issue by wgb1990** [banzaicloud/logging-operator#726]
Is your feature request related to a problem? Please describe.

We have some pod logs that are not standard output, and some pod logs with large log volume are output to external storage volume, and I found that the current logging operator does not support custom configuration of fluent bit collection configuration.

Describe the solution you'd like

Does fluent bit support sidecar deployment in the future ？

**Comment by SureshGoli123** [comment]
We are also having similar requirement for example, we want to collect log files of cloud resources (e.g: AWS ALB access logs, AWS RDS,Azure AppGW logs , etc...)

**Comment by bshifter** [comment]
Since logging-extensions is merged into logging-operator you are able to collect logs from external storage with hosttailer. The tailer-webhook feature also supports sidecars.
Check documentation here:
* https://banzaicloud.com/docs/one-eye/logging-operator/configuration/extensions/kubernetes-host-tailer/
* https://banzaicloud.com/docs/one-eye/logging-operator/configuration/extensions/tailer-webhook/

or take a look on the example file in the repository:
[config/samples/extensions/logging-extensions_v1alpha1_hosttailer.yaml](https://github.com/banzaicloud/logging-operator/blob/master/config/samples/extensions/logging-extensions_v1alpha1_hosttailer.yaml)
